# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('value', models.FloatField(default=0)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'indicators_uf',
                'ordering': ['date'],
            },
        ),
    ]
