# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uf',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
